export const WHATSAPP_SESSION_WINDOW_MS = 24 * 60 * 60 * 1000;

export const SLA_DEFAULT_RESPONSE_MINUTES = 15;
export const SLA_DEFAULT_WARNING_MINUTES = 10;

export const MAX_TEMPLATE_MESSAGE_LENGTH = 1500;
